business_project/urls.py
from django.contrib import admin
from django.urls import include, path
from pages import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('account/', include('account.urls')),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.QuestionDetailView.as_view(), name='question_detail'),
    path('comment-add/<int:pk>', views.CreateCommentView.as_view(), name='create_comment'),
    path('ask-question/', views.AskedQuestionFormView.as_view(), name='form_page'),
    path('answer-question/<int:pk>', views.AnswerQuestionFormView.as_view(), name='answer_question'),
    path('tags', views.TagView.as_view(), name='tags'),
    path('tag_detail/<str:name>', views.TagView.as_view(), name='tag_detail'),
    path('question-vote-ajax/<int:question_id>', views.QuestionVoteAjaxView.as_view(), name='question_vote_ajax'),
    path('answer-vote-ajax/<int:answer_id>', views.AnswerVoteAjaxView.as_view(), name='answer_vote_ajax'),
    path('delete-item/<str:item_type>/<int:pk>', views.DeleteItemView, name="delete_item"),
    path('timeline/<int:pk>', views.TimelineView.as_view(), name='timeline'),
    path('user-profile/<str:username>', views.UsersProfileView.as_view(), name='user_profile'),
    path('user-profile-activity/<str:username>', views.UsersProfileActivityView.as_view(), name='user_profile_activity'),
    path('user-profile-answers/<str:username>', views.UsersProfileAnswersView.as_view(), name='user_profile_answers'),
    path('user-profile-questions/<str:username>', views.UsersProfileQuestionsView.as_view(), name='user_profile_questions'),
    path('user-profile-tags/<str:username>', views.UsersProfileTagsView.as_view(), name='user_profile_tags'),
    path('get-report', views.GetReportView.as_view(), name='get_report'),
]

account/forms.py
from django import forms
from django.contrib.auth.models import User
from account.models import UserProfile
from ckeditor.widgets import CKEditorWidget

class registerForms(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 27rem; border: 1px solid black;'}), label='Kullanıcı adı :')
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'style': 'width: 27rem; border: 1px solid black;'}), label='E-posta :')
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'style': 'width: 13rem; border: 1px solid black;'}), label='parola :')
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'style': 'width: 13rem; border: 1px solid black;'}), label='parola tekrar :')
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2',)



class loginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 20rem; border: 1px solid black;'}), label='Kullanıcı adı :')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'style': 'width: 20rem; border: 1px solid black;'}), label='parola :')
    class Meta:
        model = User
        fields = ('username', 'password',)




class profileForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }), label='Kullanıcı adı:', required=False)
    profile_picture = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}), label='profil fotoğrafı: ',required=False)
    about = forms.CharField(widget=CKEditorWidget(attrs={'class': 'form-control'}), label='hakkında:', required=False)
    class Meta:
        model = UserProfile
        fields = ('username', 'profile_picture', 'about',)

pages/forms.py
from django import forms
from .models import Answers, Questions, AnswerComments, Tags, QuestionComments
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django.contrib.auth.models import User


class questionForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 49rem; border: 1px solid black;'}), label='Başlık:')
    context = forms.CharField(widget=CKEditorUploadingWidget(attrs={'class': 'form-control', 'style': 'width: 100%; border: 1px solid black;'}), label='Soru Detayı:')
    tags = forms.ModelMultipleChoiceField(queryset=Tags.objects.all(), widget=forms.SelectMultiple(attrs={'class': 'selectpicker form-control', 'data-live-search': 'true', 'data-title': 'lütfen etiket seçiniz...'}), label='Etiketler:')

    class Meta:
        model = Questions
        fields = ['title', 'context', 'tags']

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(questionForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        question = super(questionForm, self).save(commit=False)
        question.user = self.user
        if commit:
            question.save()
        return question
    


class answerForm(forms.ModelForm):
    answer = forms.CharField(widget=CKEditorUploadingWidget(attrs={'class': 'form-control', 'style': 'width: 60rem; border: 1px solid black;'}), label='Cevabınız ')
    class Meta:
        model = Answers
        fields = ('answer',)

    def __init__(self, user=None, question=None, *args, **kwargs):
        self.user = user
        self.question = question
        super(answerForm, self).__init__(*args, **kwargs)
    
    def save(self, commit=True):
        answer = super(answerForm, self).save(commit=False)
        answer.user = self.user
        answer.answer_to_the_question = self.question
        if commit:
            answer.save()
        return answer
    



class AnswerCommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'size': '10',
                                                           'class': 'form-control',
                                                           'style': 'border: 1px solid rgb(190, 190, 190); position: relative; left: 3rem; width: 45rem; height: 8rem; z-index: 3;', 'id': 'answerCommentField'}), label='Yorum ekle:')
    class Meta:
        model = AnswerComments
        fields = ('comment', )


    def __init__(self, comment=None, user=None, *args, **kwargs):
        super(AnswerCommentForm, self).__init__(*args, **kwargs)
        self.comment = comment
        self.user = user

    def save(self, commit=True):
        comment = super(AnswerCommentForm, self).save(commit=False)
        comment.comment_answer = self.comment
        comment.comment_user = self.user
        if commit:
            comment.save()
        return comment



class QuestionCommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={'size': '10',
                                                           'class': 'form-control',
                                                           'style': 'border: 1px solid rgb(190, 190, 190); position: absolute; top: 31rem; left: 36rem; width: 45rem; height: 8rem; z-index: 3;', 'id': 'questionCommentField'}), label='Yorum :', initial="1234567890")
    class Meta:
        model = QuestionComments
        fields = ('comment', )


    def __init__(self, comment=None, user=None, *args, **kwargs):
        super(QuestionCommentForm, self).__init__(*args, **kwargs)
        self.comment = comment
        self.user = user

    def save(self, commit=True):
        comment = super(QuestionCommentForm, self).save(commit=False)
        comment.comment_user = self.user
        comment.comment_question = self.comment
        if commit:
            comment.save()
        return comment

templates/pages/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %}question-detail{% endblock %}

{% block css_files %}
<style>
    .container_question {
        display: flex;
        justify-content: center;
        padding-left: 100px;
    }


    .tag {
        display: inline-block;
        text-decoration: none;
        color: rgb(24, 67, 206);
        background: #c7dbe2;
        width: 70px;
        height: 20px;
        border-radius: 5px;
        text-align: center;
        transform: translateY(-30px);
        font-size: small;
    }


    .card_question {
        position: absolute;
        top: 5rem;
        left: 31rem;
        font-size: 33px;
        font-weight: 400;
    }

    textarea {
        position: fixed;
        right: 250px;
    }

    .stil {
        color: gray;
        transition: .5s ease;
        text-decoration: none;
        cursor: pointer;
    }

    .stil:hover {
        color: blue;
    }

    .border-color {
        border: 1px solid black;
        border-radius: 50%;
        width: 35px;
        height: 35px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .border-color:hover {
        background-color: #f7d99e;
    }

    label[for="id_answer"] {
        border-top: 1px solid #ccc;
        width: 100%;
        font-size: larger;
        padding-top: 10px;
    }


    .history {
        text-decoration: none;
        color: gray;
        transition: .3s ease;
    }

    .history:hover {
        color: blue;
        opacity: 1;
    }

    .green {
        background: lightgreen;
    }

    .gray {
        background: #ccc;
    }
</style>
{% endblock %}

{% block context %}

<div class="container container_question">
    <div class="col-12">

        <div class="card_question" style="display: flex; align-items: center;">
            <p>{{ question.title }}</p>
            <a href="{% url 'form_page' %}" class="btn btn-primary" style="position: absolute; left: 50rem; width: 6rem;">Soru sor</a>
        </div>

        <div style="position: absolute; top: 9rem; left: 31rem; font-size: 15px; border-bottom: 1px solid rgb(190, 190, 190); margin-right: 7rem; width: 47%; padding-bottom: 15px;">
            Diye sordu <strong>{{ question.published_date }}</strong> tarihinde&nbsp;&nbsp;&nbsp;<strong>{{ question.view }}</strong> kez görüntülendi
        </div>

        <div style="position: absolute; top: 13rem; left: 31.7rem; font-size: larger; text-align: center;">
            <a style="text-decoration: none; color: black;" onclick="toggleQuestionVote('{{question.id}}', 'increase')"> <i class="fa-solid fa-caret-up border-color"></i></a> <br>
            <div style="position: absolute; top: 3rem; left: 0.7rem; font-size: 23px; font-weight: 600;"><p id="voteText{{question.id}}">{{ question.vote }}</p></div> <br>
            <a style="text-decoration: none; color: black;"  onclick="toggleQuestionVote('{{question.id}}', 'decrease')"><i class="fa-solid fa-caret-down border-color"></i></a> <br>
        </div>

        <div style="position: absolute; top: 22rem; left: 32.2rem;">
            <a href="{% url 'is_saved' pk=question.id %}"><i style="color: gray; font-size: 25px;" onclick="toggleSaved(this)" class="fas fa-bookmark {% if question.id in saved_que %} text-danger {% endif %}" type="button"></i></a>
        </div>

        <div style="position: absolute; top: 25rem; left: 32.3rem; font-size: 17px; opacity: 0.8;">
            <a class="history" href="{% url 'timeline' question.id %}"><i class="fa-solid fa-clock-rotate-left"></i></a>
        </div>

        <div style="position: absolute; left: 36rem; top: 12rem; width: 50%; word-wrap: break-word; overflow: auto; height: 210px;">
            <p class="card-text h6">{{ question.context|safe }}</p><br>
        </div>

        <div style="position: relative; top: 430px; left: 180px;">
            {% for tag in tags %}
                <a href="{% url 'tag_detail' tag.name %}" class="tag" style="display: inline-block; margin-right: 5px;">{{ tag.name }}</a>
            {% endfor %}
        </div>



        <div style="position: absolute; top: 10.5rem; left: 98rem; font-size: 20px;">

            <p>Bağlantılı</p>
            {% if connected|length == 0 %}
                <div style="font-size: 15px; background: lightgray; border-radius: 5px; padding: 0 10px; width: 250px;">
                    Bağlantılı soru bulunmamaktadır !
                </div>
            {% endif %}

            {% for connect in connected %}
                <div style="font-size: 15px; margin-bottom: 5px;"> <span class="{% if connect.vote <= 0 %} gray {% endif %} green" style="border: 1px solid #a8a8a8; padding: 0 15px; margin-right: 15px; border-radius: 5px;">{{connect.vote}}</span>
                    <a href="{% url 'question_detail' connect.id %}" style="text-decoration: none;">{{connect.title}}</a><br>
                </div>
            {% endfor %}

            <p style="position: relative; top: 5rem;">İlgili</p>
            {% if related|length == 0 %}
                <div style="font-size: 15px; background: lightgray; border-radius: 5px; padding: 0 10px; width: 250px; margin-top: 6rem;">
                    İlgili soru bulunmamaktadır !
                </div>
            {% endif %}

            {% for relate in related %}
                <div style="font-size: 15px; margin-bottom: 10px; position: relative; top: 75px; display: flex;">
                    <span class="{% if relate.vote <= 0 %} gray {% endif %} green" style="border: 1px solid #a8a8a8; padding: 0 15px; margin-right: 15px; border-radius: 5px; height: 25px;">{{relate.vote}}</span>
                    <a href="{% url 'question_detail' relate.id %}" style="text-decoration: none; word-wrap: break-word; width: 150px;">{{relate.title}}</a><br>
                </div>
            {% endfor %}
        </div>

            <div style="opacity: 0; transition: 0.1s ease;" id="cmnt_field">
               <form action="{% url 'create_comment' question.id %}" method="post" id="questionCommentForm">
                    {% csrf_token %}
                    {{ queCommentForm.comment }}
                    <a type="button" role="button" class="btn btn-primary" style="position: absolute; top: 36.5rem; right: 32.5rem;" onclick="commentAdd('{{question.id}}', 'questionComment')">gönder</a>
               </form>
            </div>



        <div id="commentsDiv" style="transition: 0.3s ease; margin: auto;">
            <div class="col-12" id="comments">
                {% for comment in question_comments %}
                    <div id="queComment{{ comment.id }}" style="width: 50rem; position: relative; top: 32rem; left: 12rem; border-top: 1px solid rgb(190, 190, 190); word-wrap: break-word; padding: 5px 20px 5px 20px;">
                        <p>{{ comment.comment }} - {{ comment.comment_user }} &nbsp; <em style="opacity: 0.5;">{{ comment.published_date }}</em>{% if comment.comment_user == request.user or request.user.is_superuser %}<a class="stil" onclick="commentDelete('question_comment', '{{comment.id}}', 'questionComment')" style="float: right; cursor: pointer;">Sil</a>{% endif %}</p>
                    </div>
                {% endfor %}

                <a onclick="displayChange()" id="cmnt_button" class="stil" style="position: absolute; top: 28rem; left: 36rem;"><p style="opacity: 0.8; font-size: large; cursor: pointer;">Yorum Ekle</p></a>

                {% if question.user == request.user or request.user.is_superuser %}
                    <a href="{% url 'delete_item' item_type='question' pk=question.id %}" class="stil" style="position: absolute; top: 28rem; left: 44rem;"><p style="opacity: 0.8; font-size: large;">Sil</p></a>
                {% endif %}

                <span style="position: absolute; left: 80rem; top: 27rem;">{{ question.user.username }}<br>{{ question.published_date|naturaltime }}</span>
            </div>

            <div id="answer_section" style="position: absolute; z-index: -1;">
                <div style="margin-top: 32rem; margin-left: 7rem;">

                    {% if answers|length != 0 %}
                        <div style="font-size: 25px;">{{ answer_count }} yanıt</div>
                    {% endif %}

                    {% for answer in answers %}
                        <div style="width: 800px; margin-top: 10rem; {% if forloop.first %}margin-top: 20px;{% endif %}border-top: 1px solid #ccc; padding: 10px;">
                            <div style="font-size: larger; text-align: center; width: 2.5rem;">
                                <a style="text-decoration: none; color: black;"  onclick="toggleAnswerVote('{{answer.id}}', 'increase')"><i class="fa-solid fa-caret-up border-color"></i></a><br>
                                <div style="font-size: 23px; font-weight: 600; float: left;"><p id="answerVoteText{{answer.id}}" style="margin: -1rem 0 -1rem 0.7rem;">{{ answer.vote }}</p></div><br>
                                <a style="text-decoration: none; color: black;"  onclick="toggleAnswerVote('{{answer.id}}', 'decrease')"><i class="fa-solid fa-caret-down border-color"></i></a><br>
                            </div>
                        </div>

                        <div class="col-12" style="width: 50rem; margin: -150px 0 0 70px; word-wrap: break-word;">
                            <p style="position: absolute; top: 0; left: 10rem;">{{ answer.answer|safe }}</p>
                        </div>

                        <a onclick="ansDisplayChange('{{answer.id}}')" id="ans_cmnt_button" class="stil" style="display: block; margin: 10rem 0 -48px 40px;"> <p style="opacity: 0.8; font-size: large; width: 6rem; cursor: pointer;">Yorum Ekle</p></a>

                        {% if answer.user == request.user or request.user.is_superuser %}
                            <a href="{% url 'delete_item' item_type='answer' pk=answer.id %}" class="stil" style="display: block; position: relative; top: 0.3rem; left: 10rem; opacity: 0.8; font-size: large; width: 1.5rem;">Sil</a>
                        {% endif %}

                        <span style="position: relative; left: 45rem; top: -1rem;">{{ answer.user.username }}<br>{{ answer.published_date|naturaltime }}</span>

                        <div style="display: none; transition: 0.1s ease;" id="ans_cmnt_field{{answer.id}}">
                            <form action="{% url 'create_comment' answer.id %}" method="post" id="answerCommentForm{{answer.id}}">
                                {% csrf_token %}
                                {{ ansCommentForm.comment }}
                                <a type="submit" role="button" class="btn btn-primary" style="position: relative; top: -2.5rem; left: 48.5rem;" onclick="commentAdd('{{answer.id}}', 'answerComment')">gönder</a>
                            </form>
                        </div>

                        <div id="answer_comment_field{{answer.id}}">
                            {% for comment in answer.answer_comments.all|dictsortreversed:"published_date" %}
                                <div id="answerCommentField{{comment.id}}" style="border-top: 1px solid #ccc; margin: 60px 0 -60px 50px; padding: 5px 20px 5px 20px; word-wrap: break-word; width: 50rem;">
                                    <p>{{ comment.comment }} - {{ comment.comments_user }} &nbsp; <em style="opacity: 0.5;">{{ comment.published_date }}</em>{% if comment.comments_user == request.user or request.user.is_superuser %}<a onclick="commentDelete('answer_comment', '{{comment.id}}', 'answerComment')" class="stil" style="float: right; cursor: pointer;">Sil</a>{% endif %}</p>
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>



                <div style="position: absolute; left: 7rem; margin-top: 5rem;" id="answer_field">
                    <form action="{% url 'answer_question' question.id %}" method="post">
                        {% csrf_token %}
                        <p><label style="width: 800px;" for="{{ form.answer.id_for_label }}">Cevabınız :</label></p>
                        <p>{{ form.answer }}</p>
                        {{ form.media }}
                        <div>
                            <button type="submit" class="btn btn-primary">Yanıtınızı Gönderin</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% block js_files %}
    <script>
        function toggleSaved(icon) {
            icon.classList.toggle("fas");
            icon.classList.toggle("far");
            icon.classList.toggle("text-danger");
        }
    
        function displayChange() {
            const cmntField = document.getElementById('cmnt_field');
            const cmnt = document.getElementById('commentsDiv');
    
            if (cmntField.style.opacity === '0') {
                cmntField.style.opacity = '1'
                cmnt.style.marginTop = '7rem'
            }
            else {
                cmntField.style.opacity = '0'
                cmnt.style.marginTop = '0'
            }
        }
    
        function ansDisplayChange(item_id) {
            const ansCmntField = document.getElementById('ans_cmnt_field' + item_id);
    
            if (ansCmntField.style.display === 'none') {
                ansCmntField.style.display = 'block'
            } else {
                ansCmntField.style.display = 'none'
            }
        }
        

    </script>
    <script src="{% static 'ajax.js' %}"></script>
{% endblock js_files %}
{% endblock context %}

templates/pages/get_report.html
{% extends 'base.html' %}

{% block title %}
get_report
{% endblock %}

{% block css_files %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
<style>
    .box {
        display: grid;
        position: absolute;
        top: 12rem;
        left: 36rem;
        border: 1px solid #a8a8a8;
        padding: 10rem;
        border-radius: 10px;
    }
</style>
{% endblock %}

{% block context %}
<div class="container">
    <div style="position: absolute; top: 8rem; left: 36.5rem;">
        {% for msg in messages %}
            {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="alert alert-success" style="width: 52rem; transition: 0.5s ease-in-out;">{{msg}}</div>
            {% endif %}
            {% if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="alert alert-danger" style="width: 52rem; transition: 0.5s ease-in-out;">{{msg}}</div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="box">
        <p style="position: absolute; padding: 20px;">NOT:<br>eğer tarih seçerseniz seçtiğiniz tarihe ait sorular e-posta adresinize pdf formatında gelecektir.
            Tarih seçmeden rapor al butonuna basarsanız size ait tüm sorular e-posta adresinize pdf formatında gelecektir.</p>
        <form action="{% url 'get_report' %}" method="POST">
            {% csrf_token %}
            <label class="form-label" style="font-weight: 500; font-size: 17px;" for="dateInput">Tarih : </label>
            <input class="form-control" style="width: 33rem; height: 3rem; border: 1px solid #a8a8a8;" type="date"  id="dateInput" name="selected_date">
            <button type="submit" style="position: absolute; top: 20rem; left: 19rem; width: 15rem;" class="btn btn-primary" id="get_report_btn" onclick="clickEvents()">rapor al</button>
        </form>
    </div>
</div>
{% block js_files %}
<script>
    getReportBtn = document.getElementById('get_report_btn')
    alert = document.querySelector('.alert')
    
    if (getReportBtn) {
        setTimeout (function clickEvents () {
            if (alert) {
                alert.style.opacity = 0
            }
        }, 2000)
    }
    

    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>
{% endblock %}
{% endblock %}

templates/pages/login.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'account/login.css' %}">
{% endblock %}

 {% block title %}login{% endblock %}

 {% block context %}
 <div class="container d-flex justify-content-center">

    {% if error %}
        <div class="alert alert-danger" style="margin-top: 7rem; width: 350px; text-align: center;">{{ error }}</div>
    {% endif %}

    <div class="box">
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}

            <label style="position: relative; top: 1.5rem;" class="label" for="{{ form.username.id_for_label }}">{{ form.username.label_tag }}</label>
            {{ form.username }}
            <br>
            <label style="position: relative; top: 2.5rem;" class="label" for="{{ form.password.id_for_label }}">{{ form.password.label_tag }}</label>
            {{ form.password }}
            <br>
            <div class="d-grid gap-2 mx-auto">
                <button type="submit" class="btn btn-primary btn-lg">Giriş yap</button>
            </div>
        </form>
    </div>
    <p style="position: absolute; top: 36rem;">Hesabınız yok mu?<a style="text-decoration: none;" href="{% url 'register' %}"> Bir tane oluştur</a></p>
</div>
{% endblock %}

templates/pages/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}register{% endblock %}

{% block css_files %}
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    label {
        font-weight: 700;
        font-size: 17px;
    }

    .box {
        box-shadow: 0 0 5px 1px gray;
        width: 29rem;
        height: 400px;
        display: flex;
        justify-content: center;
        position: absolute;
        border-radius: 7px;
        top: 13rem;
    }

    .btn {
        position: relative;
        top: 7rem;
    }

    input[name=username] {
        position: relative;
        top: 2rem;
    }

    input[name=email] {
        position: relative;
        top: 3rem;
    }

    input[type=password] {
        position: relative;
        top: 4rem;
    }
</style>
{% endblock %}

{% block context %}
<div class="container d-flex justify-content-center">

    {% if error %}
        <div class="alert alert-danger" style="margin-top: 8.5rem; width: 29rem; text-align: center;">{{ error }}</div>
    {% endif %}


    <div class="box">
        <form action="{% url 'register' %}" method="post">
            {% csrf_token %}
            <label style="position: relative; top: 1.5rem;" for="{{ form.username.id_for_label }}">{{ form.username.label_tag }}</label>
            <input type="text" name="username" value="{{username}}" class="form-control" required style="width: 27rem; border: 1px solid black;" id="id_username">
            <br>
        
            <label style="position: relative; top: 2.5rem;" for="{{ form.email.id_for_label }}">{{ form.email.label_tag }}</label>
            <input type="email" name="email" value="{{email}}" class="form-control" required style="width: 27rem; border: 1px solid black;" id="id_email">
            <br>
        
            <div class="row">
                <div class="col">
                    <label style="position: relative; top: 3.5rem;" for="{{ form.password1.id_for_label }}">{{ form.password1.label_tag }}</label>
                    {{ form.password1 }}
                </div>
        
                <div class="col">
                    <label style="position: relative; top: 3.5rem;" for="{{ form.password2.id_for_label }}">{{ form.password2.label_tag }}</label>
                    {{ form.password2 }}
                </div>
            </div>
        
            <div class="d-grid gap-2 mx-auto">
                <button style="position: relative; top: 6.5rem;" type="submit" class="btn btn-primary btn-lg">Kayıt ol</button>
            </div>
        </form>
    </div>
    <p style="position: absolute; top: 39rem;">Hesabınız var mı?<a style="text-decoration: none;" href="{% url 'login' %}"> Giriş yap</a></p>
</div>
{% endblock %}